### ISSUE TITLE
Library link error (I think)

### ISSUE THREAD

**Issue by rkuper** [wchen329/class#3]
When building the loader on the cae machines, one of the compile steps fails with:

cd build; g++ cload_entry.o AFU.o shell_cload.o runtime_call.o mmem.o -L. -lmtcore -lopae-c -luuid -lopae-cxx-core -lMPF-cxx -lMPF -o ../bin/cload
/usr/bin/ld: cannot find -lopae-c
/usr/bin/ld: cannot find -lopae-cxx-core
/usr/bin/ld: cannot find -lMPF-cxx
/usr/bin/ld: cannot find -lMPF
collect2: error: ld returned 1 exit status
Makefile:49: recipe for target 'bin/cload' failed
make: *** [bin/cload] Error 1

**Comment by wchen329** [comment]
Hmm so the linker tries to find the libraries using the LD_LIBRARY_PATH environment variable. Are you running with the ASE tools setup script we provided?

By the way, if you are building on CAE rather than DevCloud, you'll probably want to build target **bin/cload_sim** instead of **bin/cload** since **bin/cload_sim** actually links to the correct libraries for doing ASE simulation.

**Comment by wchen329** [comment]
That's something I'll add to the README.md. It's kind of out of date.

**Comment by rkuper** [comment]
Oh I see. I had tools setup script in my bashrc, but I do think it was a LD_LIBRARY_PATH issue. I did change cload to $(BIN_DIR)/cload_sim and now works, thanks!
